cscw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
]

game/models.py
import uuid
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator

def createUUID():
    d = uuid.uuid4()
    number = d.int
    return int(str(number)[:16])


class GameState(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)


class RoundState(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

class Client(models.Model):
    id = models.AutoField(primary_key=True)
    channel_name = models.CharField(max_length=255)

class Game(models.Model):
    game_code = models.CharField(primary_key=True, max_length=18, default=createUUID, unique=True)
    name = models.CharField(max_length=200)
    players = models.IntegerField(default=0)
    maxPlayers = models.IntegerField(validators=[MinValueValidator(3),MaxValueValidator(10)], default=3)
    round = models.IntegerField(default=0)
    maxRounds = models.IntegerField(validators=[MinValueValidator(4),MaxValueValidator(120)], default=9)
    waitSeconds = models.IntegerField(validators=[MinValueValidator(30),MaxValueValidator(600)], default=300)
    gameState = models.ForeignKey(GameState, on_delete=models.SET_NULL, blank=True, null=True, default=1)
    roundState = models.ForeignKey(RoundState, on_delete=models.SET_NULL, blank=True, null=True)
    createdAt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def getGameById(req_game_code):
        g = Game(game_code=req_game_code)
        return g


class Player(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    playerPosition = models.IntegerField()
    playing = models.IntegerField(default=0)
    points = models.IntegerField(default=0)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    playerState = models.ForeignKey(GameState, on_delete=models.SET_NULL, blank=True, null=True, default=1)

    def __str__(self):
        return self.name


class WordCard(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.CharField(max_length=200)
    deckNumber = models.IntegerField()
    used = models.BooleanField(default=False)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    createdBy = models.ForeignKey(Player, related_name='createdBy', on_delete=models.CASCADE)
    onPlayerHand = models.ForeignKey(Player, related_name='onPlayerHand', on_delete=models.CASCADE, null=True, blank=True,)

    def __str__(self):
        return self.content

class PlayerName(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    used = models.BooleanField(default=False)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    
    @classmethod
    def randomUnusedNameForGame(cls, game_inst):
        randomUnusedName = cls.objects.filter(game=game_inst, used=False).order_by('?').first()    
        return randomUnusedName

    def __str__(self):
        return self.name


class Sentence(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.CharField(max_length=1024)
    valid = models.BooleanField(default=False)
    reject = models.BooleanField(default=False)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    createdBy = models.ForeignKey(Player, on_delete=models.CASCADE)
    createdAt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

game/views/game_state_views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from ..models import GameState
from ..forms import GameStateForm
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import Http404


class GameStateListView(ListView):
    model = GameState
    template_name = "game/game_state_list.html"
    paginate_by = 20
    context_object_name = "game_state_list"
    allow_empty = True
    page_kwarg = 'page'
    paginate_orphans = 0

    def __init__(self, **kwargs):
        return super(GameStateListView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(GameStateListView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(GameStateListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return super(GameStateListView, self).get_queryset()

    def get_allow_empty(self):
        return super(GameStateListView, self).get_allow_empty()

    def get_context_data(self, *args, **kwargs):
        ret = super(GameStateListView, self).get_context_data(*args, **kwargs)
        return ret

    def get_paginate_by(self, queryset):
        return super(GameStateListView, self).get_paginate_by(queryset)

    def get_context_object_name(self, object_list):
        return super(GameStateListView, self).get_context_object_name(object_list)

    def paginate_queryset(self, queryset, page_size):
        return super(GameStateListView, self).paginate_queryset(queryset, page_size)

    def get_paginator(self, queryset, per_page, orphans=0, allow_empty_first_page=True):
        return super(GameStateListView, self).get_paginator(queryset, per_page, orphans=0, allow_empty_first_page=True)

    def render_to_response(self, context, **response_kwargs):
        return super(GameStateListView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GameStateListView, self).get_template_names()


class GameStateDetailView(DetailView):
    model = GameState
    template_name = "game/game_state_detail.html"
    context_object_name = "game_state"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'

    def __init__(self, **kwargs):
        return super(GameStateDetailView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(GameStateDetailView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(GameStateDetailView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super(GameStateDetailView, self).get_object(queryset)

    def get_queryset(self):
        return super(GameStateDetailView, self).get_queryset()

    def get_slug_field(self):
        return super(GameStateDetailView, self).get_slug_field()

    def get_context_data(self, **kwargs):
        ret = super(GameStateDetailView, self).get_context_data(**kwargs)
        return ret

    def get_context_object_name(self, obj):
        return super(GameStateDetailView, self).get_context_object_name(obj)

    def render_to_response(self, context, **response_kwargs):
        return super(GameStateDetailView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GameStateDetailView, self).get_template_names()


class GameStateCreateView(CreateView):
    model = GameState
    form_class = GameStateForm
    # fields = ['name']
    template_name = "game/game_state_create.html"
    success_url = reverse_lazy("game_state_list")

    def __init__(self, **kwargs):
        return super(GameStateCreateView, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        return super(GameStateCreateView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(GameStateCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(GameStateCreateView, self).post(request, *args, **kwargs)

    def get_form_class(self):
        return super(GameStateCreateView, self).get_form_class()

    def get_form(self, form_class=None):
        return super(GameStateCreateView, self).get_form(form_class)

    def get_form_kwargs(self, **kwargs):
        return super(GameStateCreateView, self).get_form_kwargs(**kwargs)

    def get_initial(self):
        return super(GameStateCreateView, self).get_initial()

    def form_invalid(self, form):
        return super(GameStateCreateView, self).form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        return super(GameStateCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ret = super(GameStateCreateView, self).get_context_data(**kwargs)
        return ret

    def render_to_response(self, context, **response_kwargs):
        return super(GameStateCreateView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GameStateCreateView, self).get_template_names()

    def get_success_url(self):
        return reverse("game:game_state_detail", args=(self.object.pk,))


class GameStateUpdateView(UpdateView):
    model = GameState
    form_class = GameStateForm
    # fields = ['name']
    template_name = "game/game_state_update.html"
    initial = {}
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'
    context_object_name = "game_state"

    def __init__(self, **kwargs):
        return super(GameStateUpdateView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(GameStateUpdateView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(GameStateUpdateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(GameStateUpdateView, self).post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super(GameStateUpdateView, self).get_object(queryset)

    def get_queryset(self):
        return super(GameStateUpdateView, self).get_queryset()

    def get_slug_field(self):
        return super(GameStateUpdateView, self).get_slug_field()

    def get_form_class(self):
        return super(GameStateUpdateView, self).get_form_class()

    def get_form(self, form_class=None):
        return super(GameStateUpdateView, self).get_form(form_class)

    def get_form_kwargs(self, **kwargs):
        return super(GameStateUpdateView, self).get_form_kwargs(**kwargs)

    def get_initial(self):
        return super(GameStateUpdateView, self).get_initial()

    def form_invalid(self, form):
        return super(GameStateUpdateView, self).form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        return super(GameStateUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ret = super(GameStateUpdateView, self).get_context_data(**kwargs)
        return ret

    def get_context_object_name(self, obj):
        return super(GameStateUpdateView, self).get_context_object_name(obj)

    def render_to_response(self, context, **response_kwargs):
        return super(GameStateUpdateView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GameStateUpdateView, self).get_template_names()

    def get_success_url(self):
        return reverse("game:game_state_detail", args=(self.object.pk,))


class GameStateDeleteView(DeleteView):
    model = GameState
    template_name = "game/game_state_delete.html"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'
    context_object_name = "game_state"

    def __init__(self, **kwargs):
        return super(GameStateDeleteView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(GameStateDeleteView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        raise Http404

    def post(self, request, *args, **kwargs):
        return super(GameStateDeleteView, self).post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return super(GameStateDeleteView, self).delete(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super(GameStateDeleteView, self).get_object(queryset)

    def get_queryset(self):
        return super(GameStateDeleteView, self).get_queryset()

    def get_slug_field(self):
        return super(GameStateDeleteView, self).get_slug_field()

    def get_context_data(self, **kwargs):
        ret = super(GameStateDeleteView, self).get_context_data(**kwargs)
        return ret

    def get_context_object_name(self, obj):
        return super(GameStateDeleteView, self).get_context_object_name(obj)

    def render_to_response(self, context, **response_kwargs):
        return super(GameStateDeleteView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GameStateDeleteView, self).get_template_names()

    def get_success_url(self):
        return reverse("game:game_state_list")

game/views/general_views.py
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from ..models import Game

class HomePageView(TemplateView):
    def get(self, request, **kwargs):
       # Game.objects.all().delete()
        latest_games_list = Game.objects.order_by('-createdAt')[:5]

        context = {'latest_games_list': latest_games_list,}
        return render(request, 'index.html', context)


class AboutPageView(TemplateView):
    template_name = "about.html"

game/templates/game/game_base.html
{% extends "base.html" %}

game/templates/game/game_delete.html
{% extends "game/game_base.html" %}

{% block title %}
    Delete {{ game }}
{% endblock %}

{% block content %}
<h1>Delete {{ game }}</h1>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete {{ game }}?</p>
    <input type="submit" value="Confirm" />
</form>

<a href={% url "game:game_detail" game.pk %}>Cancel</a>

{% endblock %}

game/templates/game/game_detail.html
{% extends "oneCol.html" %}
{% load bootstrap4 %}

{% block title %}{{ game }}{% endblock %}

{% block pagetitle %}Game "{{ game }}"{% endblock %}

{% block firstcardtitle %}Information{% endblock %}

{% block firstcardbody %}
    <p>Gamenumber: {{ game.game_code }}</p>
    <p>Players: {{ game.players}}/{{game.maxPlayers }}</p>
    <p>Max. Rounds: {{ game.maxRounds }}</p>
    <p>Created at: {{ game.createdAt }}</p>
{% endblock %}

{% block extrarow %}
    {% if request.session.gameID == game.game_code and request.session.playerID > 0 %}
        <a  style="margin-top: 10px;" class="flex-fill btn btn-success btn-lg btn-block" role="button" href={% url "game:game_lobby" game.pk %}>Go to Game</a>
    {% elif game.players == game.maxPlayers%}
        <a  style="margin-top: 10px;" class="flex-fill btn btn-success btn-lg btn-block disabled" role="button" href={% url "game:game_lobby" game.pk %}>Game is Full</a>
    {% else %}
        <a  style="margin-top: 10px;" class="flex-fill btn btn-success btn-lg btn-block" role="button" href={% url "game:game_join" game.pk %}>Join the game</a>
    {% endif %}

{% endblock %}

game/templates/game/game_join.html
{% extends "oneCol.html" %}
{% load bootstrap4 %}

{% block title %}Join{% endblock %}

{% block pagetitle %}Join a Game{% endblock %}

{% block firstcardtitle %}Choose a Playername{% endblock %}

{% block firstcardbody %}
    <form action="" method="post">{% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" {% if game.players == game.maxPlayers%} disabled {% endif %} value="{% if game.players == game.maxPlayers%} Game is Full {% else %}Enter the game{% endif %}" class="d-inline btn btn-primary"/>
    <input onClick="location=location.href" type="button" {% if game.players == game.maxPlayers%} disabled hidden aria-hidden {% endif %} value="{% if game.players == game.maxPlayers%} Game is Full {% else %}Suggest another name.{% endif %}" class="d-inline btn btn-secondary"/>
    </form>
    
{% endblock %}

{% block extrarow %}
{% endblock %}

game/templates/game/game_state_detail.html
{% extends "game/game_state_base.html" %}

{% block title %}
    {{ game_state }}
{% endblock %}

{% block content %}
    <h1><a href={% url "game:game_state_list" %}>GameState</a></h1>
    <h2>{{ game_state }} | <a href={% url "game:game_state_update" game_state.pk %}>Update</a> | 
    <form style="display:inline;" action={% url "game:game_state_delete" game_state.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ game_state }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
    </form>
    </h2>
{% endblock %}

game/templates/game/play_ground.html
{% extends "twoColRow.html" %}
{% load bootstrap4 %}

{% block title %}
    {{ game }}
{% endblock %}

{% block pagetitle %}Playing in "{{ game }}"{% endblock %}

{% block pagetitlebuttons %}
{% endblock %}

{% block firstcardtitle %}The Story{% endblock %}
{% block firstcardbody %}

    <p>
            {% for sentence in sentence_list %}

                    {{sentence.content}}

            {% endfor %}
    </p>



{% endblock %}

{% block secondcardtitle %}Players{% endblock %}
{% block secondcardbody %}
        <p>
     {% if game.players > 0 %}
        <ul class="list-group">
            {% for player in player_list %}
                <li class="list-group-item">{{ player.name }}</li>
            {% endfor %}
        </ul>
    {% else %}
        No players so far.
    {% endif %}
          </p>

{% endblock %}

{% block thirdcardtitle %}Pending Sentence{% endblock %}
{% block thirdcardbody %}
 {%if  State == "pending" %}
    {{ sentence_list.last}}
{% endif %}

{% endblock %}


{% block sixthcardtitle %}Your new Sentence{% endblock %}

{% block sixthcardbody %}

 {%if State == "play"  %}

    <form action="" method="post">{% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Send" name="Sentence" class="d-inline btn btn-primary"/>
    </form>

 {% endif %}
{% endblock %}


{% block fifthcardtitle %}Action Panel{% endblock %}
{% block fifthcardbody %}





    {%if State == "pending"  %}

        <script>
        var countDown = new Date().getTime();
        var x = setInterval(function() {
            var now = new Date().getTime();
            var distance = -(now-countDown);
            var seconds = Math.floor((-distance % (1000 * 60)) / 1000);

            document.getElementsByName("Accept")[0].value = "Accept [" + (10 -seconds) + "s]";




            if (seconds > 9) {
                clearInterval(x);
                document.getElementsByName("Accept")[0].click();
            }
        }, 1010);
        </script>

        <form action="" method="post">{% csrf_token %}


            <input  style="height:70px;width:180px" type="submit" id="Accept" name="Accept" value="Accept" class="d-inline btn btn-success"/>
            <input style="height:70px;width:180px" type="submit" name="Claim" value="Claim" class="d-inline btn btn-danger"/>

        </form>


    {% else %}

        <input style="height:70px;width:180px" type="submit" value="Accept" class="d-inline btn btn-lg disabled"/>
        <input style="height:70px;width:180px" type="submit" value="Claim" class="d-inline btn btn-lg disabled"/>

    {% endif %}




{% endblock %}



{% block fourthcardtitle %}Word Bank{% endblock %}
{% block fourthcardbody %}
    {% if wordCards %}
        <ul class="list-group">
        {% for word in wordCards %}
            <li>{{ word }}</li>
        {% endfor %}
        </ul>
        {% else %}
            <p>To be written!</p>
    {% endif %}
{% endblock %}


{% block extrarow %}
 {%if State == "ready" or State == "done"  %}
<script type="text/javascript">

    window.onload = setupRefresh;

    function setupRefresh() {
      setTimeout("refreshPage();", 1000); // milliseconds
    }
    function refreshPage() {
       window.location = location.href;
    }
  </script>

  {% endif %}
{% endblock %}

game/templates/game/player_create.html
{% extends "game/player_base.html" %}

{% block title %}
    Create Player
{% endblock %}

{% block content %}
<h1><a href={% url "game:player_list" %}>Player</a></h1>
<h2>Create Player</h2>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<a href={% url "game:player_list" %}>Cancel</a>
{% endblock %}

game/templates/game/player_update.html
{% extends "game/player_base.html" %}

{% block title %}
    Update {{ player }}
{% endblock %}

{% block content %}
<h1><a href={% url "game:player_list" %}>Player</a></h1>
<h2>Update {{ player }}</h2>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href={% url "game:player_detail" player.pk %}>Cancel</a>
<form style="display:inline;" action={% url "game:player_delete" player.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ player }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
</form>
{% endblock %}

game/templates/game/round_state_update.html
{% extends "game/round_state_base.html" %}

{% block title %}
    Update {{ round_state }}
{% endblock %}

{% block content %}
<h1><a href={% url "game:round_state_list" %}>RoundState</a></h1>
<h2>Update {{ round_state }}</h2>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href={% url "game:round_state_detail" round_state.pk %}>Cancel</a>
<form style="display:inline;" action={% url "game:round_state_delete" round_state.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ round_state }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
</form>
{% endblock %}

game/templates/game/sentence_base.html
{% extends "base.html" %}

game/templates/game/sentence_detail.html
{% extends "game/sentence_base.html" %}

{% block title %}
    {{ sentence }}
{% endblock %}

{% block content %}
    <h1><a href={% url "game:sentence_list" %}>Sentence</a></h1>
    <h2>{{ sentence }} | <a href={% url "game:sentence_update" sentence.pk %}>Update</a> | 
    <form style="display:inline;" action={% url "game:sentence_delete" sentence.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ sentence }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
    </form>
    </h2>
{% endblock %}

game/templates/game/sentence_list.html
{% extends "game/sentence_base.html" %}

{% block title %}
    Sentences
{% endblock %}

{% block content %}
    <h1>Sentences</h1>
    <h2><a href={% url "game:sentence_create" %}>Create new Sentence</a></h2>
    <ul>
    {% for sentence in sentence_list %}
        <li><a href={% url "game:sentence_detail" sentence.pk %}>{{ sentence }}</a> | <a href={% url "game:sentence_update" sentence.pk %}>Update</a> | <form style="display:inline;" action={% url "game:sentence_delete" sentence.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ sentence }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
    </form></li>
    {% empty %}
        <li>No Sentences yet.</li>
    {% endfor %}
    </ul>
{% endblock %}

game/templates/game/sentence_update.html
{% extends "game/sentence_base.html" %}

{% block title %}
    Update {{ sentence }}
{% endblock %}

{% block content %}
<h1><a href={% url "game:sentence_list" %}>Sentence</a></h1>
<h2>Update {{ sentence }}</h2>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href={% url "game:sentence_detail" sentence.pk %}>Cancel</a>
<form style="display:inline;" action={% url "game:sentence_delete" sentence.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ sentence }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
</form>
{% endblock %}

game/templates/game/word_card_list.html
{% extends "game/word_card_base.html" %}

{% block title %}
    WordCards
{% endblock %}

{% block content %}
    <h1>WordCards</h1>
    <h2><a href={% url "game:word_card_create" %}>Create new WordCard</a></h2>
    <ul>
    {% for word_card in word_card_list %}
        <li><a href={% url "game:word_card_detail" word_card.pk %}>{{ word_card }}</a> | <a href={% url "game:word_card_update" word_card.pk %}>Update</a> | <form style="display:inline;" action={% url "game:word_card_delete" word_card.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ word_card }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
    </form></li>
    {% empty %}
        <li>No WordCards yet.</li>
    {% endfor %}
    </ul>
{% endblock %}